
[module]
  name = "NameSmall"
  games = [ "FE7U", "FE8U" ]

[[module.statics]]
  name = "NameSmall_Static"
  file = "NameSmall.lyn.event"

[[module.internals]]
  file = "SmallFont/SmallFont.event"

[[module.asm_definitions]]
  name = "NEED_clzsi2"
  value = 1

[[module.internals]]
  file = "LibraryFunctions/LibraryFunctions.event"

# `NAME_` definitions are shared between all of the `Name` modules.
# To decouple this module's definitions from the other `Name`
# modules, override the `NAME_SMALL_` definitions in your config.

[[module.definitions]]
  name = "NAME_X"
  value = 1

[[module.definitions]]
  name = "NAME_Y"
  value = 1

[[module.definitions]]
  name = "NAME_WIDTH"
  value = 7

[[module.definitions]]
  name = "NAME_COLOR"
  value = "TEXT_COLOR_BLACK"

[[module.definitions]]
  name = "NAME_ALIGNMENT"
  value = "NAME_CENTERED"

[[module.definitions]]
  name = "NAME_SMALL_BASE_TILE_0"
  value = 0x160

[[module.definitions]]
  name = "NAME_SMALL_BASE_TILE_1"
  value = 0x165

[[module.definitions]]
  name = "NAME_SMALL_COLOR"
  value = "NAME_COLOR"

[[module.definitions]]
  name = "NAME_SMALL_X"
  value = "NAME_X"

[[module.definitions]]
  name = "NAME_SMALL_Y"
  value = "NAME_Y"

[[module.definitions]]
  name = "NAME_SMALL_ALIGNMENT"
  value = "NAME_CENTERED"

[[module.definitions]]
  name = "NAME_SMALL_WIDTH"
  value = "NAME_WIDTH"

[[module.definitions]]
  name = "NAME_SMALL_SHIFT_CONDITION"
  value = "( GetUnitAffinityIcon(udp->unit) > 0 )"

[[module.definitions]]
  name = "NAME_SMALL_SHIFT"
  value = 16

[[module.definitions]]
  name = "NAME_SMALL_SHIFT_CONDITION_DECLS"
  body = "int GetUnitAffinityIcon(struct Unit* unit);"

[[module.definitions]]
  name = "NameAlignments"
  body = '''
enum NameAlignments
{
  NAME_CENTERED,
  NAME_LEFT_ALIGNED,
  NAME_RIGHT_ALIGNED,
  NAME_SHIFTED_RIGHT,
};
'''

[[module.asm_definitions]]
  name = "GetStringFromIndex"
  body = "SET_FUNC GetStringFromIndex, 0x08013AD0 | 1"
  games = [ "FE6J" ]

[[module.asm_definitions]]
  name = "GetUnitAffinityIcon"
  body = "SET_FUNC GetUnitAffinityIcon, 0x08022F44 | 1"
  games = [ "FE6J" ]

[[module.asm_definitions]]
  name = "gGenericBuffer"
  body = "SET_DATA gGenericBuffer, 0x0201F0E8"
  games = [ "FE6J" ]


[[module.asm_definitions]]
  name = "GetStringFromIndex"
  body = "SET_FUNC GetStringFromIndex, 0x08012C60 | 1"
  games = [ "FE7U" ]

[[module.asm_definitions]]
  name = "String_ExpandNames"
  body = "SET_FUNC String_ExpandNames, 0x08012CBC | 1"
  games = [ "FE7U" ]

[[module.asm_definitions]]
  name = "GetUnitAffinityIcon"
  body = "SET_FUNC GetUnitAffinityIcon, 0x08026B24 | 1"
  games = [ "FE7U" ]

[[module.asm_definitions]]
  name = "gGenericBuffer"
  body = "SET_DATA gGenericBuffer, 0x02020140"
  games = [ "FE7U" ]


[[module.asm_definitions]]
  name = "GetStringFromIndex"
  body = "SET_FUNC GetStringFromIndex, 0x08013318 | 1"
  games = [ "FE7J" ]

[[module.asm_definitions]]
  name = "String_ExpandNames"
  body = "SET_FUNC String_ExpandNames, 0x08013374 | 1"
  games = [ "FE7J" ]

[[module.asm_definitions]]
  name = "GetUnitAffinityIcon"
  body = "SET_FUNC GetUnitAffinityIcon, 0x08026FB0 | 1"
  games = [ "FE7J" ]

[[module.asm_definitions]]
  name = "gGenericBuffer"
  body = "SET_DATA gGenericBuffer, 0x02020140"
  games = [ "FE7J" ]


[[module.asm_definitions]]
  name = "GetStringFromIndex"
  body = "SET_FUNC GetStringFromIndex, 0x0800A240 | 1"
  games = [ "FE8U" ]

[[module.asm_definitions]]
  name = "String_ExpandNames"
  body = "SET_FUNC String_ExpandNames, 0x0800A2A4 | 1"
  games = [ "FE8U" ]

[[module.asm_definitions]]
  name = "GetUnitAffinityIcon"
  body = "SET_FUNC GetUnitAffinityIcon, 0x080286BC | 1"
  games = [ "FE8U" ]

[[module.asm_definitions]]
  name = "gGenericBuffer"
  body = "SET_DATA gGenericBuffer, 0x02020188"
  games = [ "FE8U" ]


[[module.asm_definitions]]
  name = "GetStringFromIndex"
  body = "SET_FUNC GetStringFromIndex, 0x08009FA8 | 1"
  games = [ "FE8J" ]

[[module.asm_definitions]]
  name = "String_ExpandNames"
  body = "SET_FUNC String_ExpandNames, 0x0800A004 | 1"
  games = [ "FE8J" ]

[[module.asm_definitions]]
  name = "GetUnitAffinityIcon"
  body = "SET_FUNC GetUnitAffinityIcon, 0x08028650 | 1"
  games = [ "FE8J" ]

[[module.asm_definitions]]
  name = "gGenericBuffer"
  body = "SET_DATA gGenericBuffer, 0x02020188"
  games = [ "FE8J" ]
